name: Call Reusable Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  call-reusable-workflow:
    uses: resharable-workflow/.github/workflows/reusable-workflow.yaml@main
    with:
      app_language: python
      docker_image_name: pavan095/github_action_docker_python
      docker_image_tag: 1.0.0
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

